print("이름을 입력하세요:")
name = input()
print("학번을 입력하세요:")
studentId = input()
print("팀 이름을 입력하세요:")
teamname = input()

print("<출력>")
print("이름 :", name)
print("학번 :", studentId)
print("팀 이름!!:", teamname)
